export type PricingRow = {
  season: string;
  months: string;
  price: string;
};

export type LocationTag = "Mallorca" | "Ibiza" | "Formentera";
export type BoatType = "Catamaran" | "Motor Yacht" | "Sailboat";
export type Brand = "Hütter" | "Other";
export type CharterType = "day" | "week";

export type Yacht = {
  id: string;
  name: string;
  type: string;
  brand: Brand;
  locationTag: LocationTag;
  additionalLocations?: LocationTag[];
  boatType: BoatType;
  charterType: CharterType;
  location: string;
  length: string;
  dayGuests: number;
  overnightGuests: number;
  cabins: number;
  crew: number;
  dayPrice: number; // reference price for sorting (lowest season, day rate or week÷7)
  displayPrice: string; // shown on card, e.g. "FROM €1,815/day"
  image: string;
  images: string[];
  shortDescription: string;
  description: string;
  features: string[];
  waterToys?: string[];
  specs: { label: string; value: string }[];
  pricing: PricingRow[];
  included: string[];
  notIncluded: string[];
};

export const fleet: Yacht[] = [
  {
    id: "dr-no",
    name: "House of Hütter Dr. No",
    type: "Modern Power Catamaran (Hütter GT)",
    brand: "Hütter",
    locationTag: "Mallorca",
    boatType: "Catamaran",
    charterType: "day",
    location: "Palma, Mallorca",
    dayPrice: 1815,
    displayPrice: "FROM €1,815/day",
    length: "38' / 12m",
    dayGuests: 12,
    overnightGuests: 4,
    cabins: 2,
    crew: 1,
    image: "/images/hutter/dr-no/dr-no-hero.jpg",
    images: [
      "/images/hutter/dr-no/dr-no-hero.jpg",
      "/images/hutter/dr-no/dr-no-1.jpg",
      "/images/hutter/dr-no/dr-no-2.jpg",
      "/images/hutter/dr-no/dr-no-3.jpg",
      "/images/hutter/dr-no/dr-no-4.jpg",
      "/images/hutter/dr-no/dr-no-5.jpg",
      "/images/hutter/dr-no/dr-no-6.jpg",
      "/images/hutter/dr-no/dr-no-7.jpg",
      "/images/hutter/dr-no/dr-no-8.jpg",
      "/images/hutter/dr-no/dr-no-9.jpg",
    ],
    shortDescription: "Modern Power Catamaran · 38ft · 12 Day Guests",
    description:
      "House of Hütter Dr. No is a striking modern power catamaran that embodies a bold, contemporary approach to multihull design. Her wide beam and twin-hull configuration deliver excellent stability, efficiency, and generous onboard volume, creating a calm and comfortable experience both underway and at anchor. Designed with simplicity and functionality in mind, the layout maximises natural light throughout the interior. Accommodation is arranged across two cabins, including an owner's cabin and a guest cabin, making her ideal for private cruising or relaxed escapes at sea. Expansive deck spaces encourage seamless indoor–outdoor living, offering ample room for lounging, socialising, and taking in the surrounding scenery. Clean lines, modern materials, and refined minimalism define the aesthetic on board, while the twin-engine setup ensures smooth handling and efficient cruising. Distinctive and innovative, House of Hütter Dr. No presents a compelling alternative to traditional monohull motor yachts, appealing to those seeking contemporary design, inherent catamaran stability, and a refined on-water experience.",
    features: [
      "Twin Mercury Engines",
      "Modern Interior with Natural Light",
      "Comfortable Seating & Lounging Areas",
      "Dining Area with Table",
      "Professional Galley Kitchen",
      "Owner's Cabin",
      "Guest Cabin",
      "Expansive Deck Spaces",
      "Indoor / Outdoor Living",
    ],
    specs: [
      { label: "Length",           value: "38' / 12m" },
      { label: "Type",             value: "Power Catamaran" },
      { label: "Engines",          value: "Twin Mercury" },
      { label: "Cabins",           value: "2" },
      { label: "Day Guests",       value: "12" },
      { label: "Overnight Guests", value: "4" },
      { label: "Crew",             value: "1 Captain" },
      { label: "Location",         value: "Palma, Mallorca" },
    ],
    pricing: [
      { season: "Low Season",  months: "Jan – May", price: "€1,815" },
      { season: "Mid Season",  months: "Jun",       price: "€3,025" },
      { season: "High Season", months: "Jul – Aug", price: "€3,631" },
      { season: "Mid Season",  months: "Sep – Oct", price: "€3,025" },
      { season: "Low Season",  months: "Nov – Dec", price: "€1,815" },
    ],
    included: [
      "21% VAT",
      "Full Insurance",
      "Captain",
      "Home Berth",
      "Welcome Drink",
    ],
    notIncluded: ["35% APA (Fuel consumed & any extras)"],
  },
  {
    id: "moneypenny",
    name: "House of Hütter Moneypenny",
    type: "Modern Power Catamaran (Hütter GT)",
    brand: "Hütter",
    locationTag: "Mallorca",
    boatType: "Catamaran",
    charterType: "day",
    location: "Mallorca",
    dayPrice: 1815,
    displayPrice: "FROM €1,815/day",
    length: "38' / 12m",
    dayGuests: 12,
    overnightGuests: 4,
    cabins: 2,
    crew: 1,
    image: "/images/DJI_0078.jpg",
    images: [
      "/images/DJI_0078.jpg",
      "/images/DJI_0018.jpg",
      "/images/DJI_0031.jpg",
      "/images/DJI_0040.jpg",
      "/images/DJI_0053.jpg",
      "/images/DJI_0064.jpg",
      "/images/DJI_0071.jpg",
      "/images/DJI_0078-2.jpg",
      "/images/_JA40600.jpg",
      "/images/_JA40629.jpg",
    ],
    shortDescription: "Modern Power Catamaran · 38ft · 12 Day Guests",
    description:
      "House of Hütter Moneypenny is a refined modern power catamaran that reflects the brand's signature blend of contemporary design, understated luxury, and intelligent use of space. Built around a stable twin-hull platform, she offers excellent comfort underway and at anchor, making her ideal for relaxed coastal cruising and stylish days on the water. Her wide beam and balanced proportions create generous deck areas designed for effortless socialising and outdoor living. The open layout encourages a natural flow between lounging, sunbathing, and swimming, while maintaining a calm and uncluttered aesthetic defined by clean lines and premium materials. Below deck, Moneypenny features well-appointed accommodation across two cabins, providing a comfortable retreat for private cruising. The interiors are filled with natural light and finished in a modern, minimalist style that prioritises comfort, functionality, and visual harmony. With efficient twin engines, smooth handling, and the inherent stability of a catamaran, House of Hütter Moneypenny delivers a confident and enjoyable cruising experience. Distinctive yet understated, she is an appealing alternative to traditional motor yachts, perfectly suited to guests who value contemporary design, comfort, and a relaxed on-water lifestyle.",
    features: [
      "Twin Mercury Engines",
      "Modern Interior with Natural Light",
      "Comfortable Seating & Lounging Areas",
      "Dining Area with Table",
      "Professional Galley Kitchen",
      "Owner's Cabin",
      "Guest Cabin",
      "Expansive Deck Spaces",
      "Indoor / Outdoor Living",
    ],
    specs: [
      { label: "Length",           value: "38' / 12m" },
      { label: "Type",             value: "Power Catamaran" },
      { label: "Engines",          value: "Twin Mercury" },
      { label: "Cabins",           value: "2" },
      { label: "Day Guests",       value: "12" },
      { label: "Overnight Guests", value: "4" },
      { label: "Crew",             value: "1 Captain" },
      { label: "Location",         value: "Mallorca" },
    ],
    pricing: [
      { season: "Low Season",  months: "Jan – May", price: "€1,815" },
      { season: "Mid Season",  months: "Jun",       price: "€3,025" },
      { season: "High Season", months: "Jul – Aug", price: "€3,630" },
      { season: "Mid Season",  months: "Sep – Oct", price: "€3,025" },
      { season: "Low Season",  months: "Nov – Dec", price: "€1,815" },
    ],
    included: [
      "21% VAT",
      "Full Insurance",
      "Captain",
      "Home Berth",
      "Welcome Drink",
    ],
    notIncluded: ["35% APA (Fuel consumed & any extras)"],
  },
  {
    id: "goldfinger",
    name: "Goldfinger House of Hütter",
    type: "64 Catamaran (Luxury Designer Residence)",
    brand: "Hütter",
    locationTag: "Mallorca",
    boatType: "Catamaran",
    charterType: "day",
    location: "Mallorca",
    dayPrice: 5800,
    displayPrice: "FROM €5,800/day",
    length: "66' / 20m",
    dayGuests: 20,
    overnightGuests: 6,
    cabins: 3,
    crew: 2,
    image: "/images/goldfinger/1.jpg",
    images: [
      "/images/goldfinger/1.jpg",
      "/images/goldfinger/2.jpg",
      "/images/goldfinger/3.jpg",
      "/images/goldfinger/4.jpg",
      "/images/goldfinger/5.jpg",
      "/images/goldfinger/6.jpg",
      "/images/goldfinger/7.jpg",
      "/images/goldfinger/8.jpg",
      "/images/goldfinger/9.jpg",
      "/images/goldfinger/10.jpg",
      "/images/goldfinger/11.jpg",
      "/images/goldfinger/12.jpg",
      "/images/goldfinger/13.jpg",
      "/images/goldfinger/14.jpg",
      "/images/goldfinger/15.jpg",
      "/images/goldfinger/16.jpg",
      "/images/goldfinger/17.jpg",
      "/images/goldfinger/18.jpg",
      "/images/goldfinger-19.jpg",
      "/images/goldfinger-20.jpg",
      "/images/goldfinger-21.jpg",
    ],
    shortDescription: "Luxury Designer Catamaran · 66ft · 20 Day Guests · 200+ sqm",
    description:
      "GOLDFINGER is more than a yacht, it is a floating designer residence created for guests who value space, privacy and understated luxury. Tailored for the Balearics, this unique power catamaran combines the comfort of a boutique hotel with the freedom of life at sea. Offering over 200 sqm of light-filled living space, GOLDFINGER features a seamless flow between indoor and outdoor areas, allowing guests to enjoy panoramic sea views while maintaining complete privacy. Life on board is centred around relaxed luxury. Generous lounging areas and a spacious flybridge with bar and multiple chill-out zones form the social heart of the yacht, perfect for sunbathing, sunset cocktails or intimate dinners. Below deck, GOLDFINGER accommodates up to six guests in beautifully designed cabins, including a standout master suite with a private terrace and outdoor shower. Ideal for couples, families or small groups, she offers a refined and private charter experience in Mallorca, whether for day cruising or exclusive overnight stays.",
    features: [
      "200+ sqm Living Space",
      "Spacious Flybridge with Bar",
      "Multiple Chill-Out Zones",
      "Master Suite with Private Terrace",
      "Outdoor Shower",
      "Designer Residence Aesthetic",
      "Professional Galley Kitchen",
      "Panoramic Sea Views",
      "Indoor / Outdoor Living",
      "Water Toys Included",
      "Luxury Amenities Throughout",
    ],
    specs: [
      { label: "Length",           value: "66' / 20m" },
      { label: "Type",             value: "64 Catamaran" },
      { label: "Living Space",     value: "200+ sqm" },
      { label: "Cabins",           value: "3" },
      { label: "Day Guests",       value: "20" },
      { label: "Overnight Guests", value: "6" },
      { label: "Crew",             value: "2" },
      { label: "Location",         value: "Mallorca" },
    ],
    pricing: [
      { season: "High Season", months: "Jul – Aug", price: "€7,000" },
      { season: "Low Season",  months: "All other months", price: "€5,800" },
    ],
    included: [
      "21% VAT",
      "Full Insurance",
      "2 Crew",
      "Home Berth",
      "Welcome Drink",
      "Water Toys",
    ],
    notIncluded: ["35% APA (Fuel consumed & any extras)"],
  },
  {
    id: "azul",
    name: "AZUL Luxury Catamaran",
    type: "Day Charter Catamaran (Purpose-Built 2026)",
    brand: "Other",
    locationTag: "Mallorca",
    boatType: "Catamaran",
    charterType: "day",
    location: "Mallorca",
    length: "66' / 20m",
    dayGuests: 98,
    overnightGuests: 0,
    cabins: 0,
    crew: 4,
    dayPrice: 9000,
    displayPrice: "FROM €9,000/half day",
    image: "/images/azul/1.jpg",
    images: [
      "/images/azul/1.jpg",
      "/images/azul/2.jpg",
      "/images/azul/3.jpg",
      "/images/azul/4.jpg",
      "/images/azul/5.jpg",
      "/images/azul/6.jpg",
      "/images/azul/7.jpg",
      "/images/azul/8.jpg",
    ],
    shortDescription: "Day Charter Catamaran · 66ft · Up to 98 Guests · Launching 2026",
    description:
      "AZUL is a modern, purpose-built luxury day charter catamaran launching in 2026. Designed with a design-led approach to group experiences on the water, she offers three expansive decks, twin water slides, a professional sound system, and a premium onboard bar. AZUL operates below maximum capacity to ensure every guest enjoys a premium, uncrowded experience — combining the energy of a group event with the comfort and space of a private charter. Built for the discerning Mallorca day charter market, AZUL sets a new standard for large-group luxury on the Mediterranean.",
    features: [
      "Twin Water Slides",
      "Professional Sound System",
      "Premium Onboard Bar",
      "3 Expansive Decks",
      "Modern Design-Led Approach",
      "Swim Platforms & Mats",
      "Large Sun Deck",
      "Shade Areas Throughout",
    ],
    specs: [
      { label: "Length",       value: "66' / 20m" },
      { label: "Type",         value: "Day Charter Cat." },
      { label: "Day Guests",   value: "Up to 98" },
      { label: "Overnight",    value: "Day charter only" },
      { label: "Decks",        value: "3" },
      { label: "Crew",         value: "4" },
      { label: "Launch",       value: "2026" },
      { label: "Location",     value: "Mallorca" },
    ],
    pricing: [
      { season: "High Season",  months: "Jul – Aug · Half Day", price: "€12,600" },
      { season: "High Season",  months: "Jul – Aug · Full Day", price: "€24,300" },
      { season: "Mid Season",   months: "Jun, Sep · Half Day",  price: "€11,700" },
      { season: "Mid Season",   months: "Jun, Sep · Full Day",  price: "€22,500" },
      { season: "Low Season",   months: "Apr, May, Oct · Half Day", price: "€9,000" },
      { season: "Low Season",   months: "Apr, May, Oct · Full Day", price: "€17,100" },
    ],
    included: [
      "Professional Crew & Captain",
      "Soft Drinks & Water",
      "Beach Towels",
      "Swim Platforms & Mats",
    ],
    notIncluded: [
      "Premium BBQ & Open Bar Package",
      "Fuel & Port Fees",
      "Paddleboards",
      "Kayaks",
    ],
  },
  {
    id: "blue-infinity-one",
    name: "BLUE INFINITY ONE",
    type: "Motor Yacht (Sunseeker 95)",
    brand: "Other",
    locationTag: "Mallorca",
    additionalLocations: ["Ibiza", "Formentera"],
    boatType: "Motor Yacht",
    charterType: "week",
    location: "Mallorca, Ibiza & Formentera",
    length: "92' / 28m",
    dayGuests: 12,
    overnightGuests: 12,
    cabins: 5,
    crew: 4,
    dayPrice: 12143, // €85,000/week ÷ 7 for sort/filter
    displayPrice: "FROM €85,000/week",
    image: "/images/Hero.jpg",
    images: ["/images/Hero.jpg"],
    shortDescription: "Motor Yacht · 92ft · 12 Guests · Week Charter · Mallorca, Ibiza & Formentera",
    description:
      "BLUE INFINITY ONE is a luxurious Sunseeker 95 motor yacht offering unforgettable Mediterranean charters across Mallorca, Ibiza & Formentera. Featuring innovative design, opulent interiors, and state-of-the-art technology, she sets a new benchmark for private yacht charters in the Balearic Islands. Expansive outdoor spaces include a sundeck jacuzzi, plush sun loungers and a fully equipped bar. The elegant aft deck is perfectly designed for alfresco dining, while the swim platform provides direct access to the sea and a premium array of water toys. Below deck, the sophisticated interior blends contemporary style with timeless luxury — an open-plan salon with floor-to-ceiling windows, formal dining area, and five beautifully appointed cabins including a master suite with private terrace.",
    features: [
      "Jacuzzi on Sundeck",
      "Plush Sun Loungers",
      "Fully Equipped Bar",
      "Elegant Aft Deck — Alfresco Dining",
      "Swim Platform",
      "Open-Plan Salon (Floor-to-Ceiling Windows)",
      "Formal Dining Area",
      "State-of-the-Art Entertainment Systems",
      "Master Cabin with Private Terrace",
    ],
    waterToys: [
      "Williams 460 Jet Tender",
      "2x Seabob",
      "Audi E-foil",
      "Water Ski Equipment",
      "SUPs",
      "Inflatables & Towables",
      "Floating Dock / Pontoons",
      "Snorkeling Gear",
    ],
    specs: [
      { label: "Length",       value: "92' / 28m" },
      { label: "Type",         value: "Sunseeker 95" },
      { label: "Charter",      value: "Week charter" },
      { label: "Cabins",       value: "5 (Master + 4 Guest)" },
      { label: "Day Guests",   value: "12" },
      { label: "Overnight",    value: "12 guests" },
      { label: "Crew",         value: "Captain + Stew/Mate" },
      { label: "Home Port",    value: "Mallorca" },
    ],
    pricing: [
      { season: "Low Season",  months: "Apr – Jun · Oct", price: "€85,000/week" },
      { season: "High Season", months: "Jul – Sep",       price: "€95,000/week" },
    ],
    included: [
      "Captain & Stew/Mate",
      "Full Insurance",
      "Williams 460 Jet Tender",
      "2x Seabob",
      "Audi E-foil",
      "Water Ski Equipment",
      "SUPs",
      "Inflatables & Towables",
      "Floating Dock / Pontoons",
      "Snorkeling Gear",
    ],
    notIncluded: [
      "21% VAT",
      "35% APA (Fuel & Extras)",
    ],
  },
  {
    id: "ycm120",
    name: "YCM120",
    type: "Motor Yacht (ISA 36M)",
    brand: "Other",
    locationTag: "Mallorca",
    additionalLocations: ["Ibiza", "Formentera"],
    boatType: "Motor Yacht",
    charterType: "day",
    location: "Mallorca, Ibiza & Formentera",
    length: "120' / 37m",
    dayGuests: 12,
    overnightGuests: 10,
    cabins: 5,
    crew: 6,
    dayPrice: 17500,
    displayPrice: "FROM €17,500/day",
    image: "/images/ycm120-hero.jpg",
    images: ["/images/ycm120-hero.jpg"],
    shortDescription: "ISA 36M Motor Yacht · 120ft · 12 Day Guests · 6 Crew · Mallorca, Ibiza & Formentera",
    description:
      "YCM120 is an elegant ISA 36M motor yacht beautifully refitted in 2019, blending modern comfort with timeless elegance across 37 metres of exceptional charter platform. Built by International Shipyard Ancona and designed for both relaxation and entertaining, she offers expansive deck spaces ideal for sunbathing and socialising, including a Jacuzzi on deck. Her sophisticated interior creates a calm and inviting atmosphere with contemporary amenities throughout. Professionally crewed by six, YCM120 delivers personalised, attentive service as you island-hop between Mallorca, Ibiza and Formentera — discovering secluded coves and vibrant destinations in effortless luxury. Available for both day charters and week charters.",
    features: [
      "Expansive Deck Spaces",
      "Jacuzzi on Deck",
      "Sophisticated Interior",
      "Contemporary Amenities Throughout",
      "Multiple Sunbathing & Lounge Areas",
      "Alfresco Dining",
      "6 Professional Crew (Personalised Service)",
      "Island-Hopping — Mallorca, Ibiza, Formentera",
      "Refitted 2019",
      "Day Charter & Week Charter Available",
    ],
    waterToys: [
      "Axopar 30' Tender (2023)",
      "Rescue Tender 3.8m",
      "2x Jet Ski Seadoo Spark",
      "2x Sea Bobs",
      "2x Inflatable Paddle Boards",
      "2x Wakeboard",
      "Adult Water Skis",
      "Child Water Skis",
      "Wake Surf",
      "Inflatables",
      "Wetsuits",
    ],
    specs: [
      { label: "Length",       value: "120' / 37m" },
      { label: "Type",         value: "ISA 36M" },
      { label: "Refit",        value: "2019" },
      { label: "Cabins",       value: "5" },
      { label: "Day Guests",   value: "12" },
      { label: "Overnight",    value: "10 guests" },
      { label: "Crew",         value: "6 professional crew" },
      { label: "Charter",      value: "Day & Week" },
    ],
    pricing: [
      { season: "Day Charter", months: "8-hour charter",     price: "€17,500" },
      { season: "Low Season",  months: "Week charter",       price: "€98,000/week" },
      { season: "High Season", months: "Week charter",       price: "€105,000/week" },
    ],
    included: [
      "All Water Toys & Tenders",
      "Wetsuits",
      "6 Professional Crew",
      "Full Insurance (week charter)",
    ],
    notIncluded: [
      "21% VAT (week charters)",
      "35% APA — Fuel & Extras (week charters)",
      "Fuel Consumed (day charters)",
    ],
  },
  {
    id: "michisan",
    name: "Michisan",
    type: "Motor Yacht (Sanlorenzo SL90A)",
    brand: "Other",
    locationTag: "Mallorca",
    additionalLocations: ["Ibiza", "Formentera"],
    boatType: "Motor Yacht",
    charterType: "week",
    location: "Denia, Mallorca, Ibiza & Formentera",
    length: "90'6 / 27.6m",
    dayGuests: 8,
    overnightGuests: 8,
    cabins: 4,
    crew: 4,
    dayPrice: 12143, // €85,000/week ÷ 7 for sort/filter
    displayPrice: "FROM €85,000/week",
    image: "/images/michisan/1.webp",
    images: [
      "/images/michisan/1.webp",
      "/images/michisan/2.webp",
      "/images/michisan/3.webp",
      "/images/michisan/4.webp",
      "/images/michisan/5.webp",
      "/images/michisan/6.webp",
      "/images/michisan/7.webp",
      "/images/michisan/8.webp",
      "/images/michisan/9.webp",
      "/images/michisan/10.webp",
      "/images/michisan/11.webp",
      "/images/michisan/12.webp",
      "/images/michisan/13.webp",
      "/images/michisan/14.webp",
      "/images/michisan/15.webp",
      "/images/michisan/16.webp",
      "/images/michisan/17.webp",
      "/images/michisan/18.webp",
      "/images/michisan/19.webp",
      "/images/michisan/20.webp",
      "/images/michisan/21.webp",
      "/images/michisan/22.webp",
      "/images/michisan/23.webp",
      "/images/michisan/24.webp",
      "/images/michisan/25.webp",
      "/images/michisan/26.webp",
      "/images/michisan/27.webp",
    ],
    shortDescription: "Sanlorenzo SL90A · 90ft · 8 Guests · 4 Crew · Mallorca, Ibiza & Formentera",
    description:
      "MICHISAN is a contemporary Sanlorenzo SL90A motor yacht offering week charters across the Balearic Islands and the Spanish mainland from her home base in Denia. Her innovative asymmetrical layout maximises space, light and comfort throughout, creating bright, generous interiors that feel spacious well beyond her 27.6-metre length. Multiple exterior spaces invite relaxed outdoor living — from the spacious flybridge for sunbathing and relaxation, to the aft deck designed for alfresco meals, and the swim platform providing easy access to the sea. Inside, the refined main salon offers comfortable seating and indoor dining framed by large windows that maintain a constant connection with the surrounding sea. Professionally crewed by four, MICHISAN delivers attentive service throughout your charter.",
    features: [
      "Innovative Asymmetrical Layout",
      "Spacious Flybridge",
      "Aft Deck — Alfresco Dining",
      "Swim Platform",
      "Refined Light-Filled Interior",
      "Spacious Main Salon",
      "Large Windows — Natural Light",
      "Multiple Seating & Lounging Areas",
      "4 Elegant En-Suite Cabins",
      "4 Professional Crew",
    ],
    waterToys: [],
    specs: [
      { label: "Length",       value: "90'6 / 27.6m" },
      { label: "Type",         value: "Sanlorenzo SL90A" },
      { label: "Charter",      value: "Week charter" },
      { label: "Cabins",       value: "4 en-suite" },
      { label: "Day Guests",   value: "8" },
      { label: "Overnight",    value: "8 guests" },
      { label: "Crew",         value: "4 professional crew" },
      { label: "Home Base",    value: "Denia / Balearics" },
    ],
    pricing: [
      { season: "Low Season",  months: "Rest of year",       price: "€85,000/week" },
      { season: "High Season", months: "15 Jun – 15 Sep",    price: "€95,000/week" },
    ],
    included: [
      "4 Professional Crew",
      "Full Insurance",
    ],
    notIncluded: [
      "All Expenses (APA)",
      "21% VAT",
      "Fuel",
      "Port Fees",
      "Provisioning",
    ],
  },
  {
    id: "papa-mare",
    name: "PAPA MARE",
    type: "Motor Yacht (Fairline Squadron 78)",
    brand: "Other",
    locationTag: "Mallorca",
    boatType: "Motor Yacht",
    charterType: "day",
    location: "Mallorca",
    length: "79' / 24m",
    dayGuests: 8,
    overnightGuests: 8,
    cabins: 4,
    crew: 3,
    dayPrice: 7260,
    displayPrice: "FROM €7,260/day",
    image: "/images/papa-mare/1.webp",
    images: [
      "/images/papa-mare/1.webp",
      "/images/papa-mare/2.webp",
      "/images/papa-mare/3.webp",
      "/images/papa-mare/4.webp",
      "/images/papa-mare/5.webp",
      "/images/papa-mare/6.webp",
      "/images/papa-mare/7.webp",
      "/images/papa-mare/8.webp",
      "/images/papa-mare/9.webp",
      "/images/papa-mare/10.webp",
    ],
    shortDescription: "Fairline Squadron 78 · 79ft · 8 Guests · Captain, Chef & Stewardess",
    description:
      "PAPA MARE is a Fairline Squadron 78 motor yacht offering a refined charter experience in Mallorca. Featuring hand-finished living spaces, beautifully designed private staterooms and high levels of customisation, she combines elegant interiors with generous outdoor entertaining areas. The open-plan salon is bathed in natural light through panoramic windows, with comfortable seating and a formal dining area. Above, the flybridge hosts a dining area, wet bar and BBQ — perfect for long lunches at anchor. The foredeck and aft deck offer additional outdoor living close to the water, all finished with teak-laid decks and wide side walkways. Professionally crewed with Captain, Chef and Stewardess, PAPA MARE is available for day charters and week charters, offering a fully catered, all-inclusive experience on the water.",
    features: [
      "Hand-Finished Living Spaces",
      "4 Private Staterooms",
      "Open-Plan Salon with Panoramic Windows",
      "Flybridge — Dining, Wet Bar & BBQ",
      "Foredeck (Sunbathing & Dining)",
      "Aft Deck (Close to Water)",
      "Teak-Laid Decks",
      "Wide Side Walkways",
      "Dedicated Chef on Board",
      "Captain & Stewardess",
      "Day Charter & Week Charter Available",
    ],
    waterToys: [
      "Rib Tender",
    ],
    specs: [
      { label: "Length",       value: "79' / 24m" },
      { label: "Type",         value: "Fairline Squadron 78" },
      { label: "Cabins",       value: "4 staterooms" },
      { label: "Day Guests",   value: "8" },
      { label: "Overnight",    value: "8 guests" },
      { label: "Crew",         value: "Captain, Chef, Stewardess" },
      { label: "Charter",      value: "Day & Week" },
      { label: "Location",     value: "Mallorca" },
    ],
    pricing: [
      { season: "Low Season",  months: "Jan – May · Day",  price: "€7,260" },
      { season: "Mid Season",  months: "Jun · Day",        price: "€7,865" },
      { season: "High Season", months: "Jul – Aug · Day",  price: "€8,470" },
      { season: "Mid Season",  months: "Sep · Day",        price: "€7,865" },
      { season: "Low Season",  months: "Oct – Dec · Day",  price: "€7,260" },
      { season: "Low Season",  months: "Rest · Week",      price: "€36,000/week" },
      { season: "Mid Season",  months: "Jun, Sep · Week",  price: "€39,000/week" },
      { season: "High Season", months: "Jul – Aug · Week", price: "€42,000/week" },
    ],
    included: [
      "Full Insurance",
      "Captain",
      "Dedicated Chef",
      "Stewardess",
      "Rib Tender",
      "Soft Drinks",
      "21% VAT (day charters)",
    ],
    notIncluded: [
      "21% VAT (week charters)",
      "30% APA — Fuel & Extras (week charters)",
      "Premium Beverages & Food (day charters)",
    ],
  },
  {
    id: "petitchet",
    name: "PETITCHET",
    type: "Day Yacht (Fjord 52)",
    brand: "Other",
    locationTag: "Mallorca",
    boatType: "Motor Yacht",
    charterType: "day",
    location: "Mallorca",
    length: "52' / 16m",
    dayGuests: 10,
    overnightGuests: 4,
    cabins: 2,
    crew: 1,
    dayPrice: 2700,
    displayPrice: "FROM €2,700/day",
    image: "/images/petitchet-hero.jpg",
    images: [
      "/images/petitchet-hero.jpg",
      "/images/petitchet-2.jpg",
      "/images/petitchet-3.jpg",
      "/images/petitchet-4.jpg",
      "/images/petitchet-5.jpg",
      "/images/petitchet-6.jpg",
      "/images/petitchet-7.jpg",
    ],
    shortDescription: "Fjord 52 Day Yacht · 52ft · 10 Day Guests · Built 2021 · Half-Day, Full Day & Week Charters",
    description:
      "PETITCHET is a sleek Fjord 52 built in 2021, combining modern design, high cruising speeds and open-air comfort for unforgettable days on the water in Mallorca. Wide sunpads at the bow and stern, an open cockpit for alfresco dining, and a hydraulic swim platform for easy sea access make her perfect for exploring hidden calas and chic beach clubs. The T-top provides welcome shade on warm days, while panoramic views from every angle keep guests connected to the surrounding sea. She accommodates 10 guests for day charters or 4 overnight in two comfortable double cabins with one dedicated captain. Available in three formats: half-day (morning, afternoon or sunset), full-day, and week charters.",
    features: [
      "Sleek Fjord 52 Design",
      "High Cruising Speeds",
      "Wide Bow & Stern Sunpads",
      "Open Cockpit — Alfresco Dining",
      "Hydraulic Swim Platform",
      "T-Top Shade",
      "Panoramic Views",
      "2 Double Cabins (Overnight)",
      "Half-Day, Full-Day & Week Charter Options",
      "Built 2021",
    ],
    waterToys: [
      "Snorkel Equipment",
      "Paddleboard",
    ],
    specs: [
      { label: "Length",       value: "52' / 16m" },
      { label: "Type",         value: "Fjord 52" },
      { label: "Built",        value: "2021" },
      { label: "Cabins",       value: "2 double" },
      { label: "Day Guests",   value: "10" },
      { label: "Overnight",    value: "4 guests" },
      { label: "Crew",         value: "1 Captain" },
      { label: "Charter",      value: "Half-Day / Day / Week" },
    ],
    pricing: [
      { season: "Half-Day Low",  months: "Jan–Apr, Nov–Dec · Morning/Afternoon", price: "€1,620" },
      { season: "Half-Day Low",  months: "Jan–Apr, Nov–Dec · Sunset",            price: "€1,350" },
      { season: "Half-Day Mid",  months: "May–14 Jun, 15 Sep–Oct · Morning/Afternoon", price: "€1,920" },
      { season: "Half-Day Mid",  months: "May–14 Jun, 15 Sep–Oct · Sunset",      price: "€1,600" },
      { season: "Half-Day High", months: "15 Jun–14 Sep · Morning/Afternoon",    price: "€2,160" },
      { season: "Half-Day High", months: "15 Jun–14 Sep · Sunset",               price: "€1,800" },
      { season: "Full Day Low",  months: "Jan–Apr, Nov–Dec",                     price: "€2,700" },
      { season: "Full Day Mid",  months: "May–14 Jun, 15 Sep–Oct",               price: "€3,200" },
      { season: "Full Day High", months: "15 Jun–14 Sep",                        price: "€3,600" },
      { season: "Week Low",      months: "Low Season",                           price: "€15,800/week" },
      { season: "Week Mid",      months: "Mid Season",                           price: "€21,300/week" },
      { season: "Week High",     months: "High Season",                          price: "€24,200/week" },
    ],
    included: [
      "21% VAT (day charters)",
      "Full Insurance",
      "Captain",
      "Snorkel Equipment",
      "Paddleboard",
      "Soft Drinks (day charters)",
    ],
    notIncluded: [
      "Fuel Consumed",
      "21% VAT (week charters)",
      "Expenses (week charters)",
    ],
  },
  {
    id: "eternal-spark",
    name: "ETERNAL SPARK",
    type: "Luxury Motor Yacht (Bilgin 163)",
    brand: "Other",
    locationTag: "Mallorca",
    additionalLocations: ["Ibiza", "Formentera"],
    boatType: "Motor Yacht",
    charterType: "week",
    location: "Mallorca, Ibiza & Formentera",
    length: "49.95m / 163'",
    dayGuests: 12,
    overnightGuests: 12,
    cabins: 6,
    crew: 9,
    dayPrice: 47829, // €334,800/week ÷ 7 for sort/filter
    displayPrice: "FROM €334,800/week",
    image: "/images/eternal-spark-hero.jpg",
    images: [
      "/images/eternal-spark-hero.jpg",
      "/images/eternal-spark-2.jpg",
      "/images/eternal-spark-3.jpg",
      "/images/eternal-spark-4.jpg",
      "/images/eternal-spark-5.jpg",
      "/images/eternal-spark-6.jpg",
      "/images/eternal-spark-7.jpg",
      "/images/eternal-spark-8.jpg",
      "/images/eternal-spark-9.jpg",
      "/images/eternal-spark-10.jpg",
    ],
    shortDescription: "Bilgin 163 Luxury Motor Yacht · 49.95m · 12 Guests · 9 Crew · Built 2024",
    description:
      "ETERNAL SPARK is an exceptional Bilgin 163 luxury motor yacht launched in 2024, designed by Unique Yacht Design with interiors by Hot Lab. At 498 GT, she offers the space and comfort of a significantly larger vessel. Sleek exterior lines frame expansive outdoor living areas across multiple decks — from the main deck aft and bridge deck dining area to the sundeck crowned by a glass-walled Jacuzzi with panoramic sea views. The fully equipped beach club features entertainment, bar, day head, shower and an ice fountain, while the full-height Finnish sauna completes a world-class wellness offering. Inside, natural materials — stone, brass, wood, leather — blend with floor-to-ceiling windows that flood the main salon with light. The skylounge transforms into a private cinema with a 92-inch screen and surround sound system. Available for week charters across Mallorca, Ibiza and Formentera.",
    features: [
      "Sleek Exterior Lines (Unique Yacht Design)",
      "Expansive Outdoor Living Areas",
      "Main Deck Aft",
      "Bridge Deck — Dining & Socialising",
      "Sundeck with Glass-Walled Jacuzzi",
      "Fully Equipped Beach Club",
      "Full-Height Finnish Sauna",
      "Skylounge Cinema (92-inch screen & Surround Sound)",
      "Natural Materials (Stone, Brass, Wood, Leather)",
      "Floor-to-Ceiling Windows",
      "9 Professional Crew Members",
      "Built 2024",
    ],
    waterToys: [
      "Custom-Made Chase Boat",
      "Williams Sports Jet Tender",
      "2x Seadoo Spark Jetskis",
      "Jet Ski Dock",
      "2x Seabob F5 SR",
      "2x Lift Efoils",
      "4x Jobe Paddle Boards",
      "4x Lung Tank",
      "Jobe Wakeboard",
      "Jobe Towable Inflatable Couch",
      "Jobe Single Rider Towable Inflatable",
      "Snorkeling Equipment",
      "Children's Full Face Masks",
      "PFDs & Helmets",
      "Small Inflatables & Water Pistol",
    ],
    specs: [
      { label: "Length",       value: "49.95m / 163'" },
      { label: "GT",           value: "498 GT" },
      { label: "Builder",      value: "Bilgin Yachts" },
      { label: "Built",        value: "2024" },
      { label: "Cabins",       value: "6" },
      { label: "Day Guests",   value: "12" },
      { label: "Overnight",    value: "12 guests" },
      { label: "Crew",         value: "9 crew members" },
    ],
    pricing: [
      { season: "Low Season",  months: "Oct – Apr", price: "€334,800/week" },
      { season: "High Season", months: "Jun – Sep", price: "€349,800/week" },
    ],
    included: [
      "Full Insurance",
      "9 Professional Crew Members",
      "Custom-Made Chase Boat",
      "Williams Sports Jet Tender",
      "2x Seadoo Spark Jetskis",
      "2x Seabob F5 SR",
      "2x Lift Efoils",
      "4x Jobe Paddle Boards",
      "Jobe Wakeboard & Tow Toys",
      "Snorkeling Equipment",
      "Children's Full Face Masks",
      "PFDs & Helmets",
    ],
    notIncluded: [
      "21% VAT",
      "35% APA (Fuel & Extras)",
    ],
  },
];

export function getYacht(id: string): Yacht | undefined {
  return fleet.find((y) => y.id === id);
}
