export type PricingRow = {
  season: string;
  months: string;
  price: string;
};

export type LocationTag = "Mallorca" | "Ibiza" | "Formentera" | "Menorca" | "Cabrera";
export type BoatType = "Catamaran" | "Motor Yacht" | "Sailboat";
export type Brand = "Hütter" | "Other";
export type CharterType = "day" | "week";

export type Yacht = {
  id: string;
  name: string;
  type: string;
  brand: Brand;
  locationTag: LocationTag;
  additionalLocations?: LocationTag[];
  boatType: BoatType;
  charterType: CharterType;
  location: string;
  length: string;
  dayGuests: number;
  overnightGuests: number;
  cabins: number;
  crew: number;
  dayPrice: number; // reference price for sorting (lowest season, day rate or week÷7)
  displayPrice: string; // shown on card, e.g. "FROM €1,815/day"
  image: string;
  images: string[];
  shortDescription: string;
  description: string;
  features: string[];
  waterToys?: string[];
  specs: { label: string; value: string }[];
  pricing: PricingRow[];
  included: string[];
  notIncluded: string[];
};

export const fleet: Yacht[] = [
  {
    id: "dr-no",
    name: "House of Hütter Dr. No",
    type: "Modern Power Catamaran (Hütter GT)",
    brand: "Hütter",
    locationTag: "Mallorca",
    boatType: "Catamaran",
    charterType: "day",
    location: "Palma, Mallorca",
    dayPrice: 1815,
    displayPrice: "FROM €1,815/day",
    length: "38' / 12m",
    dayGuests: 12,
    overnightGuests: 4,
    cabins: 2,
    crew: 1,
    image: "/images/hutter/dr-no/dr-no-hero.jpg",
    images: [
      "/images/hutter/dr-no/dr-no-hero.jpg",
      "/images/hutter/dr-no/dr-no-1.jpg",
      "/images/hutter/dr-no/dr-no-2.jpg",
      "/images/hutter/dr-no/dr-no-3.jpg",
      "/images/hutter/dr-no/dr-no-4.jpg",
      "/images/hutter/dr-no/dr-no-5.jpg",
      "/images/hutter/dr-no/dr-no-6.jpg",
      "/images/hutter/dr-no/dr-no-7.jpg",
      "/images/hutter/dr-no/dr-no-8.jpg",
      "/images/hutter/dr-no/dr-no-9.jpg",
      "/images/Dr NO/DR.NO_-13 3.JPEG",
      "/images/Dr NO/DR.NO_-18 3.JPEG",
      "/images/Dr NO/DR.NO_-21 2.JPEG",
      "/images/Dr NO/DR.NO_-23 3.JPEG",
      "/images/Dr NO/DR.NO_-35 4.JPEG",
      "/images/Dr NO/DR.NO_-41 2.JPEG",
      "/images/Dr NO/DR.NO_-43 3.JPEG",
      "/images/Dr NO/trial-14 3.JPEG",
      "/images/Dr NO/trial-2 2.JPEG",
      "/images/Dr NO/trial-6 5.JPEG",
    ],
    shortDescription: "Modern Power Catamaran · 38ft · 12 Day Guests",
    description:
      "House of Hütter Dr. No is a striking modern power catamaran that embodies a bold, contemporary approach to multihull design. Her wide beam and twin-hull configuration deliver excellent stability, efficiency, and generous onboard volume, creating a calm and comfortable experience both underway and at anchor. Designed with simplicity and functionality in mind, the layout maximises natural light throughout the interior. Accommodation is arranged across two cabins, including an owner's cabin and a guest cabin, making her ideal for private cruising or relaxed escapes at sea. Expansive deck spaces encourage seamless indoor–outdoor living, offering ample room for lounging, socialising, and taking in the surrounding scenery. Clean lines, modern materials, and refined minimalism define the aesthetic on board, while the twin-engine setup ensures smooth handling and efficient cruising. Distinctive and innovative, House of Hütter Dr. No presents a compelling alternative to traditional monohull motor yachts, appealing to those seeking contemporary design, inherent catamaran stability, and a refined on-water experience.",
    features: [
      "Twin Mercury Engines",
      "Modern Interior with Natural Light",
      "Comfortable Seating & Lounging Areas",
      "Dining Area with Table",
      "Professional Galley Kitchen",
      "Owner's Cabin",
      "Guest Cabin",
      "Expansive Deck Spaces",
      "Indoor / Outdoor Living",
    ],
    specs: [
      { label: "Length",           value: "38' / 12m" },
      { label: "Type",             value: "Power Catamaran" },
      { label: "Engines",          value: "Twin Mercury" },
      { label: "Cabins",           value: "2" },
      { label: "Day Guests",       value: "12" },
      { label: "Overnight Guests", value: "4" },
      { label: "Crew",             value: "1 Captain" },
      { label: "Location",         value: "Palma, Mallorca" },
    ],
    pricing: [
      { season: "Low Season",  months: "Jan – May", price: "€1,815" },
      { season: "Mid Season",  months: "Jun",       price: "€3,025" },
      { season: "High Season", months: "Jul – Aug", price: "€3,631" },
      { season: "Mid Season",  months: "Sep – Oct", price: "€3,025" },
      { season: "Low Season",  months: "Nov – Dec", price: "€1,815" },
    ],
    included: [
      "21% VAT",
      "Full Insurance",
      "Captain",
      "Home Berth",
      "Welcome Drink",
    ],
    notIncluded: ["35% APA (Fuel consumed & any extras)"],
  },
  {
    id: "moneypenny",
    name: "House of Hütter Moneypenny",
    type: "Modern Power Catamaran (Hütter GT)",
    brand: "Hütter",
    locationTag: "Mallorca",
    boatType: "Catamaran",
    charterType: "day",
    location: "Mallorca",
    dayPrice: 1815,
    displayPrice: "FROM €1,815/day",
    length: "38' / 12m",
    dayGuests: 12,
    overnightGuests: 4,
    cabins: 2,
    crew: 1,
    image: "/images/Dr NO/DJI_0078.jpg",
    images: [
      "/images/Dr NO/DJI_0078.jpg",
      "/images/Dr NO/DJI_0018.jpg",
      "/images/Dr NO/DJI_0031.jpg",
      "/images/Dr NO/DJI_0040.jpg",
      "/images/Dr NO/DJI_0053.jpg",
      "/images/Dr NO/DJI_0064.jpg",
      "/images/Dr NO/DJI_0071.jpg",
      "/images/Dr NO/DJI_0078-2.jpg",
    ],
    shortDescription: "Modern Power Catamaran · 38ft · 12 Day Guests",
    description:
      "House of Hütter Moneypenny is a refined modern power catamaran that reflects the brand's signature blend of contemporary design, understated luxury, and intelligent use of space. Built around a stable twin-hull platform, she offers excellent comfort underway and at anchor, making her ideal for relaxed coastal cruising and stylish days on the water. Her wide beam and balanced proportions create generous deck areas designed for effortless socialising and outdoor living. The open layout encourages a natural flow between lounging, sunbathing, and swimming, while maintaining a calm and uncluttered aesthetic defined by clean lines and premium materials. Below deck, Moneypenny features well-appointed accommodation across two cabins, providing a comfortable retreat for private cruising. The interiors are filled with natural light and finished in a modern, minimalist style that prioritises comfort, functionality, and visual harmony. With efficient twin engines, smooth handling, and the inherent stability of a catamaran, House of Hütter Moneypenny delivers a confident and enjoyable cruising experience. Distinctive yet understated, she is an appealing alternative to traditional motor yachts, perfectly suited to guests who value contemporary design, comfort, and a relaxed on-water lifestyle.",
    features: [
      "Twin Mercury Engines",
      "Modern Interior with Natural Light",
      "Comfortable Seating & Lounging Areas",
      "Dining Area with Table",
      "Professional Galley Kitchen",
      "Owner's Cabin",
      "Guest Cabin",
      "Expansive Deck Spaces",
      "Indoor / Outdoor Living",
    ],
    specs: [
      { label: "Length",           value: "38' / 12m" },
      { label: "Type",             value: "Power Catamaran" },
      { label: "Engines",          value: "Twin Mercury" },
      { label: "Cabins",           value: "2" },
      { label: "Day Guests",       value: "12" },
      { label: "Overnight Guests", value: "4" },
      { label: "Crew",             value: "1 Captain" },
      { label: "Location",         value: "Mallorca" },
    ],
    pricing: [
      { season: "Low Season",  months: "Jan – May", price: "€1,815" },
      { season: "Mid Season",  months: "Jun",       price: "€3,025" },
      { season: "High Season", months: "Jul – Aug", price: "€3,630" },
      { season: "Mid Season",  months: "Sep – Oct", price: "€3,025" },
      { season: "Low Season",  months: "Nov – Dec", price: "€1,815" },
    ],
    included: [
      "21% VAT",
      "Full Insurance",
      "Captain",
      "Home Berth",
      "Welcome Drink",
    ],
    notIncluded: ["35% APA (Fuel consumed & any extras)"],
  },
  {
    id: "goldfinger",
    name: "Goldfinger House of Hütter",
    type: "64 Catamaran (Luxury Designer Residence)",
    brand: "Hütter",
    locationTag: "Mallorca",
    boatType: "Catamaran",
    charterType: "day",
    location: "Mallorca",
    dayPrice: 5800,
    displayPrice: "FROM €5,800/day",
    length: "66' / 20m",
    dayGuests: 20,
    overnightGuests: 6,
    cabins: 3,
    crew: 2,
    image: "/images/goldfinger/1..jpg",
    images: [
      "/images/goldfinger/1..jpg",
      "/images/goldfinger/3.jpg",
      "/images/goldfinger/4.jpg",
      "/images/goldfinger/5.jpg",
      "/images/goldfinger/6.jpg",
      "/images/goldfinger/8.jpg",
      "/images/goldfinger/9.jpg",
      "/images/goldfinger/10.jpg",
      "/images/goldfinger/11.jpg",
      "/images/goldfinger/12.jpg",
      "/images/goldfinger/13.jpg",
      "/images/goldfinger/13.13.jpg",
      "/images/goldfinger/14.jpg",
      "/images/goldfinger/15.jpg",
      "/images/goldfinger/16.jpg",
      "/images/goldfinger/16.17.jpg",
      "/images/goldfinger/18.jpg",
      "/images/goldfinger/19.jpg",
    ],
    shortDescription: "Luxury Designer Catamaran · 66ft · 20 Day Guests · 200+ sqm",
    description:
      "GOLDFINGER is more than a yacht, it is a floating designer residence created for guests who value space, privacy and understated luxury. Tailored for the Balearics, this unique power catamaran combines the comfort of a boutique hotel with the freedom of life at sea. Offering over 200 sqm of light-filled living space, GOLDFINGER features a seamless flow between indoor and outdoor areas, allowing guests to enjoy panoramic sea views while maintaining complete privacy. Life on board is centred around relaxed luxury. Generous lounging areas and a spacious flybridge with bar and multiple chill-out zones form the social heart of the yacht, perfect for sunbathing, sunset cocktails or intimate dinners. Below deck, GOLDFINGER accommodates up to six guests in beautifully designed cabins, including a standout master suite with a private terrace and outdoor shower. Ideal for couples, families or small groups, she offers a refined and private charter experience in Mallorca, whether for day cruising or exclusive overnight stays.",
    features: [
      "200+ sqm Living Space",
      "Spacious Flybridge with Bar",
      "Multiple Chill-Out Zones",
      "Master Suite with Private Terrace",
      "Outdoor Shower",
      "Designer Residence Aesthetic",
      "Professional Galley Kitchen",
      "Panoramic Sea Views",
      "Indoor / Outdoor Living",
      "Water Toys Included",
      "Luxury Amenities Throughout",
    ],
    specs: [
      { label: "Length",           value: "66' / 20m" },
      { label: "Type",             value: "64 Catamaran" },
      { label: "Living Space",     value: "200+ sqm" },
      { label: "Cabins",           value: "3" },
      { label: "Day Guests",       value: "20" },
      { label: "Overnight Guests", value: "6" },
      { label: "Crew",             value: "2" },
      { label: "Location",         value: "Mallorca" },
    ],
    pricing: [
      { season: "High Season", months: "Jul – Aug", price: "€7,000" },
      { season: "Low Season",  months: "All other months", price: "€5,800" },
    ],
    included: [
      "21% VAT",
      "Full Insurance",
      "2 Crew",
      "Home Berth",
      "Welcome Drink",
      "Water Toys",
    ],
    notIncluded: ["35% APA (Fuel consumed & any extras)"],
  },
  {
    id: "azul",
    name: "AZUL Luxury Catamaran",
    type: "Day Charter Catamaran (Purpose-Built 2026)",
    brand: "Other",
    locationTag: "Mallorca",
    boatType: "Catamaran",
    charterType: "day",
    location: "Mallorca",
    length: "66' / 20m",
    dayGuests: 98,
    overnightGuests: 0,
    cabins: 0,
    crew: 4,
    dayPrice: 9000,
    displayPrice: "FROM €9,000/half day",
    image: "/images/Azul Cartamaran /1.jpg",
    images: [
      "/images/Azul Cartamaran /1.jpg",
      "/images/Azul Cartamaran /2.jpg",
      "/images/Azul Cartamaran /3.jpg",
      "/images/Azul Cartamaran /4.jpg",
      "/images/Azul Cartamaran /5.jpg",
      "/images/Azul Cartamaran /6.jpg",
      "/images/Azul Cartamaran /7.jpg",
      "/images/Azul Cartamaran /8.jpg",
    ],
    shortDescription: "Day Charter Catamaran · 66ft · Up to 98 Guests · Launching 2026",
    description:
      "AZUL is a modern, purpose-built luxury day charter catamaran launching in 2026. Designed with a design-led approach to group experiences on the water, she offers three expansive decks, twin water slides, a professional sound system, and a premium onboard bar. AZUL operates below maximum capacity to ensure every guest enjoys a premium, uncrowded experience — combining the energy of a group event with the comfort and space of a private charter. Built for the discerning Mallorca day charter market, AZUL sets a new standard for large-group luxury on the Mediterranean.",
    features: [
      "Twin Water Slides",
      "Professional Sound System",
      "Premium Onboard Bar",
      "3 Expansive Decks",
      "Modern Design-Led Approach",
      "Swim Platforms & Mats",
      "Large Sun Deck",
      "Shade Areas Throughout",
    ],
    specs: [
      { label: "Length",       value: "66' / 20m" },
      { label: "Type",         value: "Day Charter Cat." },
      { label: "Day Guests",   value: "Up to 98" },
      { label: "Overnight",    value: "Day charter only" },
      { label: "Decks",        value: "3" },
      { label: "Crew",         value: "4" },
      { label: "Launch",       value: "2026" },
      { label: "Location",     value: "Mallorca" },
    ],
    pricing: [
      { season: "High Season",  months: "Jul – Aug · Half Day", price: "€12,600" },
      { season: "High Season",  months: "Jul – Aug · Full Day", price: "€24,300" },
      { season: "Mid Season",   months: "Jun, Sep · Half Day",  price: "€11,700" },
      { season: "Mid Season",   months: "Jun, Sep · Full Day",  price: "€22,500" },
      { season: "Low Season",   months: "Apr, May, Oct · Half Day", price: "€9,000" },
      { season: "Low Season",   months: "Apr, May, Oct · Full Day", price: "€17,100" },
    ],
    included: [
      "Professional Crew & Captain",
      "Soft Drinks & Water",
      "Beach Towels",
      "Swim Platforms & Mats",
    ],
    notIncluded: [
      "Premium BBQ & Open Bar Package",
      "Fuel & Port Fees",
      "Paddleboards",
      "Kayaks",
    ],
  },
  {
    id: "blue-infinity-one",
    name: "BLUE INFINITY ONE",
    type: "Motor Yacht (Sunseeker 95)",
    brand: "Other",
    locationTag: "Mallorca",
    additionalLocations: ["Ibiza", "Formentera"],
    boatType: "Motor Yacht",
    charterType: "week",
    location: "Mallorca, Ibiza & Formentera",
    length: "92' / 28m",
    dayGuests: 12,
    overnightGuests: 12,
    cabins: 5,
    crew: 4,
    dayPrice: 12143, // €85,000/week ÷ 7 for sort/filter
    displayPrice: "FROM €85,000/week",
    image: "/images/blue infinity/1.webp",
    images: [
      "/images/blue infinity/1.webp",
      "/images/blue infinity/2.webp",
      "/images/blue infinity/3.webp",
      "/images/blue infinity/4.webp",
      "/images/blue infinity/5.webp",
      "/images/blue infinity/6.webp",
      "/images/blue infinity/7.webp",
      "/images/blue infinity/8.webp",
      "/images/blue infinity/9.webp",
      "/images/blue infinity/10.webp",
      "/images/blue infinity/11.webp",
      "/images/blue infinity/12.webp",
      "/images/blue infinity/13.webp",
      "/images/blue infinity/14.webp",
      "/images/blue infinity/16.webp",
      "/images/blue infinity/17.webp",
      "/images/blue infinity/20.webp",
      "/images/blue infinity/21.webp",
      "/images/blue infinity/22.webp",
      "/images/blue infinity/23.webp",
      "/images/blue infinity/24.webp",
      "/images/blue infinity/25.webp",
      "/images/blue infinity/26.webp",
      "/images/blue infinity/27.webp",
      "/images/blue infinity/28.webp",
      "/images/blue infinity/29.webp",
      "/images/blue infinity/30.webp",
      "/images/blue infinity/31.webp",
      "/images/blue infinity/32.webp",
      "/images/blue infinity/33.webp",
      "/images/blue infinity/34.webp",
      "/images/blue infinity/35.webp",
      "/images/blue infinity/36.webp",
      "/images/blue infinity/37.webp",
      "/images/blue infinity/38.webp",
    ],
    shortDescription: "Motor Yacht · 92ft · 12 Guests · Week Charter · Mallorca, Ibiza & Formentera",
    description:
      "BLUE INFINITY ONE is a luxurious Sunseeker 95 motor yacht offering unforgettable Mediterranean charters across Mallorca, Ibiza & Formentera. Featuring innovative design, opulent interiors, and state-of-the-art technology, she sets a new benchmark for private yacht charters in the Balearic Islands. Expansive outdoor spaces include a sundeck jacuzzi, plush sun loungers and a fully equipped bar. The elegant aft deck is perfectly designed for alfresco dining, while the swim platform provides direct access to the sea and a premium array of water toys. Below deck, the sophisticated interior blends contemporary style with timeless luxury — an open-plan salon with floor-to-ceiling windows, formal dining area, and five beautifully appointed cabins including a master suite with private terrace.",
    features: [
      "Jacuzzi on Sundeck",
      "Plush Sun Loungers",
      "Fully Equipped Bar",
      "Elegant Aft Deck — Alfresco Dining",
      "Swim Platform",
      "Open-Plan Salon (Floor-to-Ceiling Windows)",
      "Formal Dining Area",
      "State-of-the-Art Entertainment Systems",
      "Master Cabin with Private Terrace",
    ],
    waterToys: [
      "Williams 460 Jet Tender",
      "2x Seabob",
      "Audi E-foil",
      "Water Ski Equipment",
      "SUPs",
      "Inflatables & Towables",
      "Floating Dock / Pontoons",
      "Snorkeling Gear",
    ],
    specs: [
      { label: "Length",       value: "92' / 28m" },
      { label: "Type",         value: "Sunseeker 95" },
      { label: "Charter",      value: "Week charter" },
      { label: "Cabins",       value: "5 (Master + 4 Guest)" },
      { label: "Day Guests",   value: "12" },
      { label: "Overnight",    value: "12 guests" },
      { label: "Crew",         value: "Captain + Stew/Mate" },
      { label: "Home Port",    value: "Mallorca" },
    ],
    pricing: [
      { season: "Low Season",  months: "Apr – Jun · Oct", price: "€85,000/week" },
      { season: "High Season", months: "Jul – Sep",       price: "€95,000/week" },
    ],
    included: [
      "Captain & Stew/Mate",
      "Full Insurance",
      "Williams 460 Jet Tender",
      "2x Seabob",
      "Audi E-foil",
      "Water Ski Equipment",
      "SUPs",
      "Inflatables & Towables",
      "Floating Dock / Pontoons",
      "Snorkeling Gear",
    ],
    notIncluded: [
      "21% VAT",
      "35% APA (Fuel & Extras)",
    ],
  },
  {
    id: "ycm120",
    name: "YCM120",
    type: "Motor Yacht (ISA 36M)",
    brand: "Other",
    locationTag: "Mallorca",
    additionalLocations: ["Ibiza", "Formentera"],
    boatType: "Motor Yacht",
    charterType: "day",
    location: "Mallorca, Ibiza & Formentera",
    length: "120' / 37m",
    dayGuests: 12,
    overnightGuests: 10,
    cabins: 5,
    crew: 6,
    dayPrice: 17500,
    displayPrice: "FROM €17,500/day",
    image: "/images/YMC120/1.webp",
    images: [
      "/images/YMC120/1.webp",
      "/images/YMC120/2.webp",
      "/images/YMC120/3.webp",
      "/images/YMC120/4.webp",
      "/images/YMC120/5.webp",
      "/images/YMC120/6.webp",
      "/images/YMC120/7.webp",
      "/images/YMC120/8.webp",
      "/images/YMC120/9.webp",
      "/images/YMC120/10.webp",
      "/images/YMC120/11.webp",
      "/images/YMC120/12.webp",
      "/images/YMC120/13.webp",
      "/images/YMC120/14.webp",
      "/images/YMC120/15.webp",
      "/images/YMC120/16.webp",
      "/images/YMC120/17.webp",
      "/images/YMC120/18.webp",
      "/images/YMC120/19.webp",
    ],
    shortDescription: "ISA 36M Motor Yacht · 120ft · 12 Day Guests · 6 Crew · Mallorca, Ibiza & Formentera",
    description:
      "YCM120 is an elegant ISA 36M motor yacht beautifully refitted in 2019, blending modern comfort with timeless elegance across 37 metres of exceptional charter platform. Built by International Shipyard Ancona and designed for both relaxation and entertaining, she offers expansive deck spaces ideal for sunbathing and socialising, including a Jacuzzi on deck. Her sophisticated interior creates a calm and inviting atmosphere with contemporary amenities throughout. Professionally crewed by six, YCM120 delivers personalised, attentive service as you island-hop between Mallorca, Ibiza and Formentera — discovering secluded coves and vibrant destinations in effortless luxury. Available for both day charters and week charters.",
    features: [
      "Expansive Deck Spaces",
      "Jacuzzi on Deck",
      "Sophisticated Interior",
      "Contemporary Amenities Throughout",
      "Multiple Sunbathing & Lounge Areas",
      "Alfresco Dining",
      "6 Professional Crew (Personalised Service)",
      "Island-Hopping — Mallorca, Ibiza, Formentera",
      "Refitted 2019",
      "Day Charter & Week Charter Available",
    ],
    waterToys: [
      "Axopar 30' Tender (2023)",
      "Rescue Tender 3.8m",
      "2x Jet Ski Seadoo Spark",
      "2x Sea Bobs",
      "2x Inflatable Paddle Boards",
      "2x Wakeboard",
      "Adult Water Skis",
      "Child Water Skis",
      "Wake Surf",
      "Inflatables",
      "Wetsuits",
    ],
    specs: [
      { label: "Length",       value: "120' / 37m" },
      { label: "Type",         value: "ISA 36M" },
      { label: "Refit",        value: "2019" },
      { label: "Cabins",       value: "5" },
      { label: "Day Guests",   value: "12" },
      { label: "Overnight",    value: "10 guests" },
      { label: "Crew",         value: "6 professional crew" },
      { label: "Charter",      value: "Day & Week" },
    ],
    pricing: [
      { season: "Day Charter", months: "8-hour charter",     price: "€17,500" },
      { season: "Low Season",  months: "Week charter",       price: "€98,000/week" },
      { season: "High Season", months: "Week charter",       price: "€105,000/week" },
    ],
    included: [
      "All Water Toys & Tenders",
      "Wetsuits",
      "6 Professional Crew",
      "Full Insurance (week charter)",
    ],
    notIncluded: [
      "21% VAT (week charters)",
      "35% APA — Fuel & Extras (week charters)",
      "Fuel Consumed (day charters)",
    ],
  },
  {
    id: "michisan",
    name: "Michisan",
    type: "Motor Yacht (Sanlorenzo SL90A)",
    brand: "Other",
    locationTag: "Mallorca",
    additionalLocations: ["Ibiza", "Formentera"],
    boatType: "Motor Yacht",
    charterType: "week",
    location: "Denia, Mallorca, Ibiza & Formentera",
    length: "90'6 / 27.6m",
    dayGuests: 8,
    overnightGuests: 8,
    cabins: 4,
    crew: 4,
    dayPrice: 12143, // €85,000/week ÷ 7 for sort/filter
    displayPrice: "FROM €85,000/week",
    image: "/images/Michisan /1.webp",
    images: [
      "/images/Michisan /1.webp",
      "/images/Michisan /2.webp",
      "/images/Michisan /3.webp",
      "/images/Michisan /4.webp",
      "/images/Michisan /5.webp",
      "/images/Michisan /6.webp",
      "/images/Michisan /7.webp",
      "/images/Michisan /8.webp",
      "/images/Michisan /9.webp",
      "/images/Michisan /10.webp",
      "/images/Michisan /11.webp",
      "/images/Michisan /12.webp",
      "/images/Michisan /13.webp",
      "/images/Michisan /14.webp",
      "/images/Michisan /15.webp",
      "/images/Michisan /16.webp",
      "/images/Michisan /17.webp",
      "/images/Michisan /18.webp",
      "/images/Michisan /19.webp",
      "/images/Michisan /20.webp",
      "/images/Michisan /21.webp",
      "/images/Michisan /22.webp",
      "/images/Michisan /23.webp",
      "/images/Michisan /24.webp",
      "/images/Michisan /25.webp",
      "/images/Michisan /26.webp",
      "/images/Michisan /27.webp",
    ],
    shortDescription: "Sanlorenzo SL90A · 90ft · 8 Guests · 4 Crew · Mallorca, Ibiza & Formentera",
    description:
      "MICHISAN is a contemporary Sanlorenzo SL90A motor yacht offering week charters across the Balearic Islands and the Spanish mainland from her home base in Denia. Her innovative asymmetrical layout maximises space, light and comfort throughout, creating bright, generous interiors that feel spacious well beyond her 27.6-metre length. Multiple exterior spaces invite relaxed outdoor living — from the spacious flybridge for sunbathing and relaxation, to the aft deck designed for alfresco meals, and the swim platform providing easy access to the sea. Inside, the refined main salon offers comfortable seating and indoor dining framed by large windows that maintain a constant connection with the surrounding sea. Professionally crewed by four, MICHISAN delivers attentive service throughout your charter.",
    features: [
      "Innovative Asymmetrical Layout",
      "Spacious Flybridge",
      "Aft Deck — Alfresco Dining",
      "Swim Platform",
      "Refined Light-Filled Interior",
      "Spacious Main Salon",
      "Large Windows — Natural Light",
      "Multiple Seating & Lounging Areas",
      "4 Elegant En-Suite Cabins",
      "4 Professional Crew",
    ],
    waterToys: [],
    specs: [
      { label: "Length",       value: "90'6 / 27.6m" },
      { label: "Type",         value: "Sanlorenzo SL90A" },
      { label: "Charter",      value: "Week charter" },
      { label: "Cabins",       value: "4 en-suite" },
      { label: "Day Guests",   value: "8" },
      { label: "Overnight",    value: "8 guests" },
      { label: "Crew",         value: "4 professional crew" },
      { label: "Home Base",    value: "Denia / Balearics" },
    ],
    pricing: [
      { season: "Low Season",  months: "Rest of year",       price: "€85,000/week" },
      { season: "High Season", months: "15 Jun – 15 Sep",    price: "€95,000/week" },
    ],
    included: [
      "4 Professional Crew",
      "Full Insurance",
    ],
    notIncluded: [
      "All Expenses (APA)",
      "21% VAT",
      "Fuel",
      "Port Fees",
      "Provisioning",
    ],
  },
  {
    id: "papa-mare",
    name: "PAPA MARE",
    type: "Motor Yacht (Fairline Squadron 78)",
    brand: "Other",
    locationTag: "Mallorca",
    boatType: "Motor Yacht",
    charterType: "day",
    location: "Mallorca",
    length: "79' / 24m",
    dayGuests: 8,
    overnightGuests: 8,
    cabins: 4,
    crew: 3,
    dayPrice: 7260,
    displayPrice: "FROM €7,260/day",
    image: "/images/papa-mare/1.webp",
    images: [
      "/images/papa-mare/1.webp",
      "/images/papa-mare/2.webp",
      "/images/papa-mare/3.webp",
      "/images/papa-mare/4.webp",
      "/images/papa-mare/5.webp",
      "/images/papa-mare/6.webp",
      "/images/papa-mare/7.webp",
      "/images/papa-mare/8.webp",
      "/images/papa-mare/9.webp",
      "/images/papa-mare/10.webp",
    ],
    shortDescription: "Fairline Squadron 78 · 79ft · 8 Guests · Captain, Chef & Stewardess",
    description:
      "PAPA MARE is a Fairline Squadron 78 motor yacht offering a refined charter experience in Mallorca. Featuring hand-finished living spaces, beautifully designed private staterooms and high levels of customisation, she combines elegant interiors with generous outdoor entertaining areas. The open-plan salon is bathed in natural light through panoramic windows, with comfortable seating and a formal dining area. Above, the flybridge hosts a dining area, wet bar and BBQ — perfect for long lunches at anchor. The foredeck and aft deck offer additional outdoor living close to the water, all finished with teak-laid decks and wide side walkways. Professionally crewed with Captain, Chef and Stewardess, PAPA MARE is available for day charters and week charters, offering a fully catered, all-inclusive experience on the water.",
    features: [
      "Hand-Finished Living Spaces",
      "4 Private Staterooms",
      "Open-Plan Salon with Panoramic Windows",
      "Flybridge — Dining, Wet Bar & BBQ",
      "Foredeck (Sunbathing & Dining)",
      "Aft Deck (Close to Water)",
      "Teak-Laid Decks",
      "Wide Side Walkways",
      "Dedicated Chef on Board",
      "Captain & Stewardess",
      "Day Charter & Week Charter Available",
    ],
    waterToys: [
      "Rib Tender",
    ],
    specs: [
      { label: "Length",       value: "79' / 24m" },
      { label: "Type",         value: "Fairline Squadron 78" },
      { label: "Cabins",       value: "4 staterooms" },
      { label: "Day Guests",   value: "8" },
      { label: "Overnight",    value: "8 guests" },
      { label: "Crew",         value: "Captain, Chef, Stewardess" },
      { label: "Charter",      value: "Day & Week" },
      { label: "Location",     value: "Mallorca" },
    ],
    pricing: [
      { season: "Low Season",  months: "Jan – May · Day",  price: "€7,260" },
      { season: "Mid Season",  months: "Jun · Day",        price: "€7,865" },
      { season: "High Season", months: "Jul – Aug · Day",  price: "€8,470" },
      { season: "Mid Season",  months: "Sep · Day",        price: "€7,865" },
      { season: "Low Season",  months: "Oct – Dec · Day",  price: "€7,260" },
      { season: "Low Season",  months: "Rest · Week",      price: "€36,000/week" },
      { season: "Mid Season",  months: "Jun, Sep · Week",  price: "€39,000/week" },
      { season: "High Season", months: "Jul – Aug · Week", price: "€42,000/week" },
    ],
    included: [
      "Full Insurance",
      "Captain",
      "Dedicated Chef",
      "Stewardess",
      "Rib Tender",
      "Soft Drinks",
      "21% VAT (day charters)",
    ],
    notIncluded: [
      "21% VAT (week charters)",
      "30% APA — Fuel & Extras (week charters)",
      "Premium Beverages & Food (day charters)",
    ],
  },
  {
    id: "eternal-spark",
    name: "ETERNAL SPARK",
    type: "Luxury Motor Yacht (Bilgin 163)",
    brand: "Other",
    locationTag: "Mallorca",
    additionalLocations: ["Ibiza", "Formentera"],
    boatType: "Motor Yacht",
    charterType: "week",
    location: "Mallorca, Ibiza & Formentera",
    length: "49.95m / 163'",
    dayGuests: 12,
    overnightGuests: 12,
    cabins: 6,
    crew: 9,
    dayPrice: 47829, // €334,800/week ÷ 7 for sort/filter
    displayPrice: "FROM €334,800/week",
    image: "/images/Eternal Spark/1.1.webp",
    images: [
      "/images/Eternal Spark/1.1.webp",
      "/images/Eternal Spark/1.webp",
      "/images/Eternal Spark/2.2.webp",
      "/images/Eternal Spark/2.webp",
      "/images/Eternal Spark/3.webp",
      "/images/Eternal Spark/4.webp",
      "/images/Eternal Spark/5.webp",
      "/images/Eternal Spark/6.webp",
      "/images/Eternal Spark/7.webp",
      "/images/Eternal Spark/8.webp",
      "/images/Eternal Spark/9.webp",
      "/images/Eternal Spark/10.webp",
      "/images/Eternal Spark/11.webp",
      "/images/Eternal Spark/12.webp",
      "/images/Eternal Spark/13.webp",
      "/images/Eternal Spark/14.webp",
      "/images/Eternal Spark/16.webp",
      "/images/Eternal Spark/17.webp",
      "/images/Eternal Spark/18.webp",
      "/images/Eternal Spark/19.webp",
      "/images/Eternal Spark/20.webp",
      "/images/Eternal Spark/22.webp",
      "/images/Eternal Spark/23.webp",
      "/images/Eternal Spark/24.webp",
      "/images/Eternal Spark/25.webp",
      "/images/Eternal Spark/26.webp",
      "/images/Eternal Spark/27.webp",
      "/images/Eternal Spark/28.webp",
      "/images/Eternal Spark/29.webp",
      "/images/Eternal Spark/30.webp",
      "/images/Eternal Spark/31.webp",
      "/images/Eternal Spark/32.webp",
      "/images/Eternal Spark/33.webp",
      "/images/Eternal Spark/34.webp",
      "/images/Eternal Spark/35.webp",
      "/images/Eternal Spark/36.webp",
      "/images/Eternal Spark/37.webp",
      "/images/Eternal Spark/38.webp",
      "/images/Eternal Spark/39.webp",
      "/images/Eternal Spark/40.webp",
      "/images/Eternal Spark/41.webp",
      "/images/Eternal Spark/42.webp",
      "/images/Eternal Spark/43.webp",
    ],
    shortDescription: "Bilgin 163 Luxury Motor Yacht · 49.95m · 12 Guests · 9 Crew · Built 2024",
    description:
      "ETERNAL SPARK is an exceptional Bilgin 163 luxury motor yacht launched in 2024, designed by Unique Yacht Design with interiors by Hot Lab. At 498 GT, she offers the space and comfort of a significantly larger vessel. Sleek exterior lines frame expansive outdoor living areas across multiple decks — from the main deck aft and bridge deck dining area to the sundeck crowned by a glass-walled Jacuzzi with panoramic sea views. The fully equipped beach club features entertainment, bar, day head, shower and an ice fountain, while the full-height Finnish sauna completes a world-class wellness offering. Inside, natural materials — stone, brass, wood, leather — blend with floor-to-ceiling windows that flood the main salon with light. The skylounge transforms into a private cinema with a 92-inch screen and surround sound system. Available for week charters across Mallorca, Ibiza and Formentera.",
    features: [
      "Sleek Exterior Lines (Unique Yacht Design)",
      "Expansive Outdoor Living Areas",
      "Main Deck Aft",
      "Bridge Deck — Dining & Socialising",
      "Sundeck with Glass-Walled Jacuzzi",
      "Fully Equipped Beach Club",
      "Full-Height Finnish Sauna",
      "Skylounge Cinema (92-inch screen & Surround Sound)",
      "Natural Materials (Stone, Brass, Wood, Leather)",
      "Floor-to-Ceiling Windows",
      "9 Professional Crew Members",
      "Built 2024",
    ],
    waterToys: [
      "Custom-Made Chase Boat",
      "Williams Sports Jet Tender",
      "2x Seadoo Spark Jetskis",
      "Jet Ski Dock",
      "2x Seabob F5 SR",
      "2x Lift Efoils",
      "4x Jobe Paddle Boards",
      "4x Lung Tank",
      "Jobe Wakeboard",
      "Jobe Towable Inflatable Couch",
      "Jobe Single Rider Towable Inflatable",
      "Snorkeling Equipment",
      "Children's Full Face Masks",
      "PFDs & Helmets",
      "Small Inflatables & Water Pistol",
    ],
    specs: [
      { label: "Length",       value: "49.95m / 163'" },
      { label: "GT",           value: "498 GT" },
      { label: "Builder",      value: "Bilgin Yachts" },
      { label: "Built",        value: "2024" },
      { label: "Cabins",       value: "6" },
      { label: "Day Guests",   value: "12" },
      { label: "Overnight",    value: "12 guests" },
      { label: "Crew",         value: "9 crew members" },
    ],
    pricing: [
      { season: "Low Season",  months: "Oct – Apr", price: "€334,800/week" },
      { season: "High Season", months: "Jun – Sep", price: "€349,800/week" },
    ],
    included: [
      "Full Insurance",
      "9 Professional Crew Members",
      "Custom-Made Chase Boat",
      "Williams Sports Jet Tender",
      "2x Seadoo Spark Jetskis",
      "2x Seabob F5 SR",
      "2x Lift Efoils",
      "4x Jobe Paddle Boards",
      "Jobe Wakeboard & Tow Toys",
      "Snorkeling Equipment",
      "Children's Full Face Masks",
      "PFDs & Helmets",
    ],
    notIncluded: [
      "21% VAT",
      "35% APA (Fuel & Extras)",
    ],
  },
  {
    id: "nemesis",
    name: "NEMESIS",
    type: "Superyacht (Azimut 32 Metri)",
    brand: "Other",
    locationTag: "Mallorca",
    additionalLocations: ["Menorca", "Ibiza", "Formentera", "Cabrera"],
    boatType: "Motor Yacht",
    charterType: "week",
    location: "Mallorca · Menorca · Ibiza · Formentera · Cabrera",
    length: "105' / 32m",
    dayGuests: 12,
    overnightGuests: 10,
    cabins: 5,
    crew: 6,
    dayPrice: 17143, // €120,000/week ÷ 7
    displayPrice: "FROM €120,000/week",
    image: "/images/Nemesis Azimut 3/1.1.webp",
    images: [
      "/images/Nemesis Azimut 3/1.1.webp",
      "/images/Nemesis Azimut 3/1.webp",
      "/images/Nemesis Azimut 3/2.2.webp",
      "/images/Nemesis Azimut 3/2.webp",
      "/images/Nemesis Azimut 3/3.3.webp",
      "/images/Nemesis Azimut 3/3.webp",
      "/images/Nemesis Azimut 3/4.4.webp",
      "/images/Nemesis Azimut 3/4.webp",
      "/images/Nemesis Azimut 3/5.5.webp",
      "/images/Nemesis Azimut 3/5.webp",
      "/images/Nemesis Azimut 3/6.webp",
      "/images/Nemesis Azimut 3/7.webp",
      "/images/Nemesis Azimut 3/9.webp",
      "/images/Nemesis Azimut 3/10.webp",
      "/images/Nemesis Azimut 3/11.webp",
      "/images/Nemesis Azimut 3/12.webp",
      "/images/Nemesis Azimut 3/14.webp",
      "/images/Nemesis Azimut 3/15.webp",
      "/images/Nemesis Azimut 3/16.webp",
      "/images/Nemesis Azimut 3/19.webp",
      "/images/Nemesis Azimut 3/20.webp",
      "/images/Nemesis Azimut 3/21.webp",
      "/images/Nemesis Azimut 3/22.webp",
      "/images/Nemesis Azimut 3/23.webp",
      "/images/Nemesis Azimut 3/24.webp",
      "/images/Nemesis Azimut 3/25.webp",
      "/images/Nemesis Azimut 3/26.webp",
      "/images/Nemesis Azimut 3/27.webp",
      "/images/Nemesis Azimut 3/28.webp",
      "/images/Nemesis Azimut 3/29.webp",
      "/images/Nemesis Azimut 3/30.webp",
      "/images/Nemesis Azimut 3/32.webp",
      "/images/Nemesis Azimut 3/33.webp",
      "/images/Nemesis Azimut 3/34.webp",
      "/images/Nemesis Azimut 3/35.webp",
      "/images/Nemesis Azimut 3/36.webp",
    ],
    shortDescription: "Azimut 32 Metri Superyacht · 105ft · 12 Day Guests · 10 Overnight · 6 Crew",
    description:
      "The Azimut 32 Metri is a striking symbol of luxury and sophistication, offering refined cruising across the azure waters of the Balearic Islands. This elegant 32-metre superyacht combines sleek lines with exceptional design, balancing style and functionality. Its spacious interior is beautifully crafted with premium materials and modern amenities, creating an atmosphere of understated opulence. Comfortable seating areas, elegant cabins and advanced technology ensure a seamless experience on board. Expansive outdoor decks provide panoramic views and generous space for relaxation and entertainment, from sunbathing and alfresco dining to enjoying time on the water. With a dedicated professional crew delivering attentive, personalised service, the Azimut 32 Metri promises an unforgettable charter defined by comfort, elegance and effortless style.",
    features: [
      "Premium Interior Materials",
      "5 Elegant Cabins",
      "Professional Crew of 6",
      "Expansive Outdoor Decks",
      "Panoramic Views",
      "Al Fresco Dining",
      "Advanced Technology",
      "Modern Amenities",
    ],
    waterToys: [
      "Williams 485 Jet Tender",
      "Jet Ski",
      "2x Seabob",
      "E-Foil",
      "Inflatables & Towable Toys",
    ],
    specs: [
      { label: "Length",           value: "105' / 32m" },
      { label: "Type",             value: "Superyacht" },
      { label: "Builder",          value: "Azimut" },
      { label: "Model",            value: "32 Metri" },
      { label: "Cabins",           value: "5" },
      { label: "Day Guests",       value: "12" },
      { label: "Overnight Guests", value: "10" },
      { label: "Crew",             value: "6" },
      { label: "Location",         value: "Mallorca · Menorca · Ibiza · Formentera · Cabrera" },
    ],
    pricing: [
      { season: "High Season",  months: "Jul – Aug",              price: "€130,000/week" },
      { season: "Rest of Year", months: "Jan – Jun / Sep – Dec",  price: "€120,000/week" },
    ],
    included: [],
    notIncluded: ["All expenses"],
  },
  {
    id: "lady-m",
    name: "LADY M",
    type: "Motor Yacht (Sunseeker 76)",
    brand: "Other",
    locationTag: "Mallorca",
    boatType: "Motor Yacht",
    charterType: "day",
    location: "Mallorca",
    length: "76' / 23m",
    dayGuests: 12,
    overnightGuests: 8,
    cabins: 4,
    crew: 3,
    dayPrice: 8470,
    displayPrice: "FROM €8,470/day",
    image: "/images/lady-m/Lady M neu /1.webp",
    images: [
      "/images/lady-m/Lady M neu /1.webp",
      "/images/lady-m/Lady M neu /2.webp",
      "/images/lady-m/Lady M neu /3.webp",
      "/images/lady-m/Lady M neu /4.webp",
      "/images/lady-m/Lady M neu /5.webp",
      "/images/lady-m/Lady M neu /6.webp",
      "/images/lady-m/Lady M neu /7.webp",
      "/images/lady-m/Lady M neu /8.webp",
      "/images/lady-m/Lady M neu /9.webp",
      "/images/lady-m/Lady M neu /10.webp",
      "/images/lady-m/Lady M neu /11.webp",
      "/images/lady-m/Lady M neu /12.webp",
      "/images/lady-m/Lady M neu /13.webp",
      "/images/lady-m/Lady M neu /14.webp",
      "/images/lady-m/Lady M neu /15.webp",
    ],
    shortDescription: "Sunseeker 76 Motor Yacht · 76ft · 12 Day Guests · 8 Overnight · Built 2019 · Mallorca",
    description:
      "Meet Lady M, a 23-metre Sunseeker 76 built for stylish escapes along the Mallorcan coast. Delivered in 2019, she blends sleek design, spacious decks, and effortless performance. Unwind on the foredeck's wide sunbeds, or enjoy panoramic views with a drink in hand on the flybridge's cocktail bar. The aft deck is perfect for relaxed al fresco dining. Inside, the bright lounge and dining area offer a calm retreat, surrounded by full-length windows that invite the outdoors in. Lady M hosts up to eight guests across four elegant cabins, including a full-beam master, a VIP, and two twins that convert to doubles. With three crew members on board, everything is taken care of, so you can simply enjoy the journey.",
    features: [
      "Stabilizers",
      "Wi-Fi",
      "Premium Sound System",
      "Full-beam Master Cabin",
      "VIP Cabin",
      "Two Twin/Double Cabins",
      "Flybridge with Cocktail Bar",
      "Foredeck Sunbeds",
      "Al Fresco Dining on Aft Deck",
      "Full-length Windows",
    ],
    waterToys: [
      "Williams Jet Tender",
      "Seabob",
      "Paddleboards",
      "Snorkelling Gear",
    ],
    specs: [
      { label: "Length",           value: "76' / 23m" },
      { label: "Type",             value: "Motor Yacht" },
      { label: "Builder",          value: "Sunseeker" },
      { label: "Built",            value: "2019" },
      { label: "Cabins",           value: "4" },
      { label: "Day Guests",       value: "12" },
      { label: "Overnight Guests", value: "8" },
      { label: "Crew",             value: "3" },
      { label: "Location",         value: "Mallorca" },
    ],
    pricing: [
      { season: "Day · Low Season",   months: "Jan – Jun / Sep – Dec", price: "€8,470/day" },
      { season: "Day · High Season",  months: "Jul – Aug",             price: "€9,559/day" },
      { season: "Week · Low Season",  months: "Sep – Jun",             price: "€42,000/week" },
      { season: "Week · High Season", months: "Jul – Aug",             price: "€47,500/week" },
    ],
    included: [
      "21% VAT (day charter)",
      "Full Insurance",
      "Captain",
      "Stew / Mate",
      "Jet Tender",
      "Paddleboard",
      "Seabob",
      "Snorkel Equipment",
      "Soft Drinks",
    ],
    notIncluded: [
      "Fuel consumed",
      "Any extras",
      "Week charter: 21% VAT + 30% APA",
    ],
  },
  {
    id: "de-antonio-42",
    name: "De Antonio 42 Tot Suma",
    type: "Open Motorboat (De Antonio D42 Open)",
    brand: "Other",
    locationTag: "Ibiza",
    boatType: "Motor Yacht",
    charterType: "day",
    location: "Marina Botafoch, Ibiza",
    length: "42' / 13m",
    dayGuests: 11,
    overnightGuests: 2,
    cabins: 1,
    crew: 1,
    dayPrice: 2000,
    displayPrice: "FROM €2,000/day",
    image: "/images/fleet/de-antonio-42/1.webp",
    images: [
      "/images/fleet/de-antonio-42/1.webp",
      "/images/fleet/de-antonio-42/2.webp",
      "/images/fleet/de-antonio-42/3.webp",
      "/images/fleet/de-antonio-42/4.webp",
    ],
    shortDescription: "De Antonio D42 Open · 13m · 11 Day Guests · Built 2023 · Marina Botafoch, Ibiza",
    description:
      "De Antonio 42 Tot Suma represents refined Mediterranean cruising for guests who appreciate generous exterior spaces and effortless comfort. Built in 2023, this open yacht combines smooth performance with a calm, spacious layout ideal for day cruising between Ibiza and Formentera. The yacht's walk-around design creates a relaxed flow throughout, with shaded seating areas, an exterior lounge, and spacious foredeck providing the perfect balance of sun and shelter. Wide sunbeds at both bow and stern invite leisurely afternoons, while the interior offers intimate accommodation — ideal for overnight anchorages.",
    features: [
      "Walk-around deck design",
      "Wide bow & stern sunbeds",
      "Shaded seating areas",
      "Spacious foredeck",
      "Exterior lounge",
      "1 double cabin",
      "1 twin open cabin",
      "1 bathroom",
      "3 × 350 hp engines",
      "Bluetooth sound system",
    ],
    waterToys: ["Paddleboard", "Snorkel equipment"],
    specs: [
      { label: "Length",     value: "42' / 13m" },
      { label: "Beam",       value: "3.99m" },
      { label: "Built",      value: "2023" },
      { label: "Engines",    value: "3 × 350 hp" },
      { label: "Day Guests", value: "11 + skipper" },
      { label: "Cabins",     value: "1 double, 1 twin open" },
      { label: "Bathrooms",  value: "1" },
      { label: "Home Port",  value: "Marina Botafoch, Ibiza" },
      { label: "Skipper",    value: "Professional (included)" },
    ],
    pricing: [
      { season: "Day Charter", months: "Contact for availability", price: "From €2,000/day" },
    ],
    included: [
      "VAT",
      "Professional skipper",
      "Drinks & snacks",
      "Towels",
      "Snorkel equipment",
      "Paddleboard",
      "Sunshade & extended sunshade",
      "Portable cooler",
      "Interior & exterior seating",
      "Bluetooth sound system",
    ],
    notIncluded: ["Fuel", "Port fees"],
  },
  {
    id: "sunseeker-mohawk-29",
    name: "Sunseeker Mohawk 29 Tabung",
    type: "Classic Dayboat (Sunseeker Mohawk 29)",
    brand: "Other",
    locationTag: "Ibiza",
    boatType: "Motor Yacht",
    charterType: "day",
    location: "Marina Ibiza",
    length: "29' / 8.51m",
    dayGuests: 7,
    overnightGuests: 0,
    cabins: 1,
    crew: 1,
    dayPrice: 800,
    displayPrice: "FROM €800/day",
    image: "/images/fleet/sunseeker-mohawk-29/1.webp",
    images: [
      "/images/fleet/sunseeker-mohawk-29/1.webp",
      "/images/fleet/sunseeker-mohawk-29/2.webp",
      "/images/fleet/sunseeker-mohawk-29/3.webp",
    ],
    shortDescription: "Sunseeker Mohawk 29 · 8.51m · 7 Day Guests · Marina Ibiza · From €800/day",
    description:
      "The Sunseeker Mohawk 29 Tabung is a compact, sporty and charming yacht perfect for small groups seeking a relaxed Mediterranean day on the water. With its clean open layout, updated upholstery and classic Sunseeker profile, this yacht feels instantly comfortable from the moment you step onboard. Wide sunbeds at both bow and stern create generous lounging areas ideal for relaxing, sunbathing or taking in Ibiza's legendary coastline at a slow, effortless pace. The bimini shade and cockpit seating provide cosy social spaces, while snorkel equipment, paddleboard and premium Bluetooth audio make it easy to enjoy long swims, turquoise bays and relaxed afternoons at anchor. From Ibiza Town to the pristine bays of Formentera, the Mohawk 29 moves smoothly across Mediterranean waters — perfect for laid-back days, hidden cove exploration, or sunset cocktails with loved ones.",
    features: [
      "Compact & sporty design",
      "Wide bow & stern sunbeds",
      "Bimini shade",
      "Cockpit seating",
      "Clean open layout",
      "Updated upholstery",
      "Classic Sunseeker profile",
      "2 × 200 hp Volvo engines",
      "Bluetooth sound system",
      "Perfect for small groups",
    ],
    waterToys: ["Paddleboard", "Snorkel equipment"],
    specs: [
      { label: "Length",       value: "29' / 8.51m" },
      { label: "Beam",         value: "2.9m" },
      { label: "Engines",      value: "2 × Volvo 200 hp" },
      { label: "Day Guests",   value: "7 + captain" },
      { label: "Cabin",        value: "1 open cabin" },
      { label: "Bathrooms",    value: "1" },
      { label: "Home Port",    value: "Marina Ibiza" },
      { label: "Daily Rate",   value: "From €800/day" },
      { label: "Skipper",      value: "Professional (included)" },
    ],
    pricing: [
      { season: "Day Charter",       months: "Contact for availability", price: "From €800/day" },
      { season: "Multi-day Charter", months: "Discounts available",      price: "Contact us" },
    ],
    included: [
      "Professional skipper",
      "Towels",
      "Water, soft drinks, beer, wine & rosé",
      "Snacks",
      "Snorkel equipment",
      "Paddleboard",
      "Sunshade (bimini)",
      "Bluetooth music system",
    ],
    notIncluded: ["Fuel", "Port fees"],
  },
];

export function getYacht(id: string): Yacht | undefined {
  return fleet.find((y) => y.id === id);
}
